// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package edu.uci.ics.amber.engine.architecture.worker.workloadmetrics

object WorkloadmetricsProto extends _root_.scalapb.GeneratedFileObject {
  lazy val dependencies: Seq[_root_.scalapb.GeneratedFileObject] = Seq(
    scalapb.options.ScalapbProto,
    edu.uci.ics.amber.engine.common.virtualidentity.VirtualidentityProto
  )
  lazy val messagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] =
    Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]](
      edu.uci.ics.amber.engine.architecture.worker.workloadmetrics.Loads,
      edu.uci.ics.amber.engine.architecture.worker.workloadmetrics.SelfWorkloadSample,
      edu.uci.ics.amber.engine.architecture.worker.workloadmetrics.SelfWorkloadMetrics,
      edu.uci.ics.amber.engine.architecture.worker.workloadmetrics.SelfWorkloadReturn
    )
  private lazy val ProtoBytes: _root_.scala.Array[Byte] =
      scalapb.Encoding.fromBase64(scala.collection.immutable.Seq(
  """CkJlZHUvdWNpL2ljcy9hbWJlci9lbmdpbmUvYXJjaGl0ZWN0dXJlL3dvcmtlci93b3JrbG9hZG1ldHJpY3MucHJvdG8SLGVkd
  S51Y2kuaWNzLmFtYmVyLmVuZ2luZS5hcmNoaXRlY3R1cmUud29ya2VyGhVzY2FsYXBiL3NjYWxhcGIucHJvdG8aNWVkdS91Y2kva
  WNzL2FtYmVyL2VuZ2luZS9jb21tb24vdmlydHVhbGlkZW50aXR5LnByb3RvIoUBCgVMb2FkcxJdCgZ3b3JrZXIYASABKAsyNS5lZ
  HUudWNpLmljcy5hbWJlci5lbmdpbmUuY29tbW9uLkFjdG9yVmlydHVhbElkZW50aXR5Qg7iPwsSBndvcmtlcvABAVIGd29ya2VyE
  h0KBGxvYWQYAiADKANCCeI/BhIEbG9hZFIEbG9hZCJrChJTZWxmV29ya2xvYWRTYW1wbGUSVQoFbG9hZHMYASADKAsyMy5lZHUud
  WNpLmljcy5hbWJlci5lbmdpbmUuYXJjaGl0ZWN0dXJlLndvcmtlci5Mb2Fkc0IK4j8HEgVsb2Fkc1IFbG9hZHMixwMKE1NlbGZXb
  3JrbG9hZE1ldHJpY3MSbAohdW5wcm9jZXNzZWRfZGF0YV9pbnB1dF9xdWV1ZV9zaXplGAEgASgDQiLiPx8SHXVucHJvY2Vzc2VkR
  GF0YUlucHV0UXVldWVTaXplUh11bnByb2Nlc3NlZERhdGFJbnB1dFF1ZXVlU2l6ZRJ1CiR1bnByb2Nlc3NlZF9jb250cm9sX2luc
  HV0X3F1ZXVlX3NpemUYAiABKANCJeI/IhIgdW5wcm9jZXNzZWRDb250cm9sSW5wdXRRdWV1ZVNpemVSIHVucHJvY2Vzc2VkQ29ud
  HJvbElucHV0UXVldWVTaXplEmAKHXN0YXNoZWRfZGF0YV9pbnB1dF9xdWV1ZV9zaXplGAMgASgDQh7iPxsSGXN0YXNoZWREYXRhS
  W5wdXRRdWV1ZVNpemVSGXN0YXNoZWREYXRhSW5wdXRRdWV1ZVNpemUSaQogc3Rhc2hlZF9jb250cm9sX2lucHV0X3F1ZXVlX3Npe
  mUYBCABKANCIeI/HhIcc3Rhc2hlZENvbnRyb2xJbnB1dFF1ZXVlU2l6ZVIcc3Rhc2hlZENvbnRyb2xJbnB1dFF1ZXVlU2l6ZSLsA
  QoSU2VsZldvcmtsb2FkUmV0dXJuEmwKB21ldHJpY3MYASABKAsyQS5lZHUudWNpLmljcy5hbWJlci5lbmdpbmUuYXJjaGl0ZWN0d
  XJlLndvcmtlci5TZWxmV29ya2xvYWRNZXRyaWNzQg/iPwwSB21ldHJpY3PwAQFSB21ldHJpY3MSaAoHc2FtcGxlcxgCIAMoCzJAL
  mVkdS51Y2kuaWNzLmFtYmVyLmVuZ2luZS5hcmNoaXRlY3R1cmUud29ya2VyLlNlbGZXb3JrbG9hZFNhbXBsZUIM4j8JEgdzYW1wb
  GVzUgdzYW1wbGVzQgniPwZIAFgAeAFiBnByb3RvMw=="""
      ).mkString)
  lazy val scalaDescriptor: _root_.scalapb.descriptors.FileDescriptor = {
    val scalaProto = com.google.protobuf.descriptor.FileDescriptorProto.parseFrom(ProtoBytes)
    _root_.scalapb.descriptors.FileDescriptor.buildFrom(scalaProto, dependencies.map(_.scalaDescriptor))
  }
  lazy val javaDescriptor: com.google.protobuf.Descriptors.FileDescriptor = {
    val javaProto = com.google.protobuf.DescriptorProtos.FileDescriptorProto.parseFrom(ProtoBytes)
    com.google.protobuf.Descriptors.FileDescriptor.buildFrom(javaProto, _root_.scala.Array(
      scalapb.options.ScalapbProto.javaDescriptor,
      edu.uci.ics.amber.engine.common.virtualidentity.VirtualidentityProto.javaDescriptor
    ))
  }
  @deprecated("Use javaDescriptor instead. In a future version this will refer to scalaDescriptor.", "ScalaPB 0.5.47")
  def descriptor: com.google.protobuf.Descriptors.FileDescriptor = javaDescriptor
}