/*
 * This file is generated by jOOQ.
 */
package edu.uci.ics.texera.dataflow.jooqgenerated;


import edu.uci.ics.texera.dataflow.jooqgenerated.tables.Useraccount;


/**
 * Convenience access to all tables in texera
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>texera.UserAccount</code>.
     */
    public static final Useraccount USERACCOUNT = Useraccount.USERACCOUNT;
}
