// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package edu.uci.ics.amber.engine.architecture.rpc.controlcommands

@SerialVersionUID(0L)
final case class WorkflowReconfigureRequest(
    reconfiguration: edu.uci.ics.amber.engine.architecture.rpc.controlcommands.ModifyLogicRequest,
    reconfigurationId: _root_.scala.Predef.String
    ) extends scalapb.GeneratedMessage with scalapb.lenses.Updatable[WorkflowReconfigureRequest] {
    @transient
    private[this] var __serializedSizeMemoized: _root_.scala.Int = 0
    private[this] def __computeSerializedSize(): _root_.scala.Int = {
      var __size = 0
      
      {
        val __value = reconfiguration
        if (__value.serializedSize != 0) {
          __size += 1 + _root_.com.google.protobuf.CodedOutputStream.computeUInt32SizeNoTag(__value.serializedSize) + __value.serializedSize
        }
      };
      
      {
        val __value = reconfigurationId
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(2, __value)
        }
      };
      __size
    }
    override def serializedSize: _root_.scala.Int = {
      var __size = __serializedSizeMemoized
      if (__size == 0) {
        __size = __computeSerializedSize() + 1
        __serializedSizeMemoized = __size
      }
      __size - 1
      
    }
    def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): _root_.scala.Unit = {
      {
        val __v = reconfiguration
        if (__v.serializedSize != 0) {
          _output__.writeTag(1, 2)
          _output__.writeUInt32NoTag(__v.serializedSize)
          __v.writeTo(_output__)
        }
      };
      {
        val __v = reconfigurationId
        if (!__v.isEmpty) {
          _output__.writeString(2, __v)
        }
      };
    }
    def withReconfiguration(__v: edu.uci.ics.amber.engine.architecture.rpc.controlcommands.ModifyLogicRequest): WorkflowReconfigureRequest = copy(reconfiguration = __v)
    def withReconfigurationId(__v: _root_.scala.Predef.String): WorkflowReconfigureRequest = copy(reconfigurationId = __v)
    def getFieldByNumber(__fieldNumber: _root_.scala.Int): _root_.scala.Any = {
      (__fieldNumber: @_root_.scala.unchecked) match {
        case 1 => {
          val __t = reconfiguration
          if (__t != edu.uci.ics.amber.engine.architecture.rpc.controlcommands.ModifyLogicRequest.defaultInstance) __t else null
        }
        case 2 => {
          val __t = reconfigurationId
          if (__t != "") __t else null
        }
      }
    }
    def getField(__field: _root_.scalapb.descriptors.FieldDescriptor): _root_.scalapb.descriptors.PValue = {
      _root_.scala.Predef.require(__field.containingMessage eq companion.scalaDescriptor)
      (__field.number: @_root_.scala.unchecked) match {
        case 1 => reconfiguration.toPMessage
        case 2 => _root_.scalapb.descriptors.PString(reconfigurationId)
      }
    }
    def toProtoString: _root_.scala.Predef.String = _root_.scalapb.TextFormat.printToSingleLineUnicodeString(this)
    def companion: edu.uci.ics.amber.engine.architecture.rpc.controlcommands.WorkflowReconfigureRequest.type = edu.uci.ics.amber.engine.architecture.rpc.controlcommands.WorkflowReconfigureRequest
    // @@protoc_insertion_point(GeneratedMessage[edu.uci.ics.amber.engine.architecture.rpc.WorkflowReconfigureRequest])
}

object WorkflowReconfigureRequest extends scalapb.GeneratedMessageCompanion[edu.uci.ics.amber.engine.architecture.rpc.controlcommands.WorkflowReconfigureRequest] {
  implicit def messageCompanion: scalapb.GeneratedMessageCompanion[edu.uci.ics.amber.engine.architecture.rpc.controlcommands.WorkflowReconfigureRequest] = this
  def parseFrom(`_input__`: _root_.com.google.protobuf.CodedInputStream): edu.uci.ics.amber.engine.architecture.rpc.controlcommands.WorkflowReconfigureRequest = {
    var __reconfiguration: _root_.scala.Option[edu.uci.ics.amber.engine.architecture.rpc.controlcommands.ModifyLogicRequest] = _root_.scala.None
    var __reconfigurationId: _root_.scala.Predef.String = ""
    var _done__ = false
    while (!_done__) {
      val _tag__ = _input__.readTag()
      _tag__ match {
        case 0 => _done__ = true
        case 10 =>
          __reconfiguration = _root_.scala.Some(__reconfiguration.fold(_root_.scalapb.LiteParser.readMessage[edu.uci.ics.amber.engine.architecture.rpc.controlcommands.ModifyLogicRequest](_input__))(_root_.scalapb.LiteParser.readMessage(_input__, _)))
        case 18 =>
          __reconfigurationId = _input__.readStringRequireUtf8()
        case tag => _input__.skipField(tag)
      }
    }
    edu.uci.ics.amber.engine.architecture.rpc.controlcommands.WorkflowReconfigureRequest(
        reconfiguration = __reconfiguration.getOrElse(edu.uci.ics.amber.engine.architecture.rpc.controlcommands.ModifyLogicRequest.defaultInstance),
        reconfigurationId = __reconfigurationId
    )
  }
  implicit def messageReads: _root_.scalapb.descriptors.Reads[edu.uci.ics.amber.engine.architecture.rpc.controlcommands.WorkflowReconfigureRequest] = _root_.scalapb.descriptors.Reads{
    case _root_.scalapb.descriptors.PMessage(__fieldsMap) =>
      _root_.scala.Predef.require(__fieldsMap.keys.forall(_.containingMessage eq scalaDescriptor), "FieldDescriptor does not match message type.")
      edu.uci.ics.amber.engine.architecture.rpc.controlcommands.WorkflowReconfigureRequest(
        reconfiguration = __fieldsMap.get(scalaDescriptor.findFieldByNumber(1).get).map(_.as[edu.uci.ics.amber.engine.architecture.rpc.controlcommands.ModifyLogicRequest]).getOrElse(edu.uci.ics.amber.engine.architecture.rpc.controlcommands.ModifyLogicRequest.defaultInstance),
        reconfigurationId = __fieldsMap.get(scalaDescriptor.findFieldByNumber(2).get).map(_.as[_root_.scala.Predef.String]).getOrElse("")
      )
    case _ => throw new RuntimeException("Expected PMessage")
  }
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.Descriptor = ControlcommandsProto.javaDescriptor.getMessageTypes().get(7)
  def scalaDescriptor: _root_.scalapb.descriptors.Descriptor = ControlcommandsProto.scalaDescriptor.messages(7)
  def messageCompanionForFieldNumber(__number: _root_.scala.Int): _root_.scalapb.GeneratedMessageCompanion[_] = {
    var __out: _root_.scalapb.GeneratedMessageCompanion[_] = null
    (__number: @_root_.scala.unchecked) match {
      case 1 => __out = edu.uci.ics.amber.engine.architecture.rpc.controlcommands.ModifyLogicRequest
    }
    __out
  }
  lazy val nestedMessagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] = Seq.empty
  def enumCompanionForFieldNumber(__fieldNumber: _root_.scala.Int): _root_.scalapb.GeneratedEnumCompanion[_] = throw new MatchError(__fieldNumber)
  lazy val defaultInstance = edu.uci.ics.amber.engine.architecture.rpc.controlcommands.WorkflowReconfigureRequest(
    reconfiguration = edu.uci.ics.amber.engine.architecture.rpc.controlcommands.ModifyLogicRequest.defaultInstance,
    reconfigurationId = ""
  )
  implicit class WorkflowReconfigureRequestLens[UpperPB](_l: _root_.scalapb.lenses.Lens[UpperPB, edu.uci.ics.amber.engine.architecture.rpc.controlcommands.WorkflowReconfigureRequest]) extends _root_.scalapb.lenses.ObjectLens[UpperPB, edu.uci.ics.amber.engine.architecture.rpc.controlcommands.WorkflowReconfigureRequest](_l) {
    def reconfiguration: _root_.scalapb.lenses.Lens[UpperPB, edu.uci.ics.amber.engine.architecture.rpc.controlcommands.ModifyLogicRequest] = field(_.reconfiguration)((c_, f_) => c_.copy(reconfiguration = f_))
    def reconfigurationId: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.reconfigurationId)((c_, f_) => c_.copy(reconfigurationId = f_))
  }
  final val RECONFIGURATION_FIELD_NUMBER = 1
  final val RECONFIGURATIONID_FIELD_NUMBER = 2
  def of(
    reconfiguration: edu.uci.ics.amber.engine.architecture.rpc.controlcommands.ModifyLogicRequest,
    reconfigurationId: _root_.scala.Predef.String
  ): _root_.edu.uci.ics.amber.engine.architecture.rpc.controlcommands.WorkflowReconfigureRequest = _root_.edu.uci.ics.amber.engine.architecture.rpc.controlcommands.WorkflowReconfigureRequest(
    reconfiguration,
    reconfigurationId
  )
  // @@protoc_insertion_point(GeneratedMessageCompanion[edu.uci.ics.amber.engine.architecture.rpc.WorkflowReconfigureRequest])
}
