// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package edu.uci.ics.amber.engine.architecture.worker.controlcommands

object ControlcommandsProto extends _root_.scalapb.GeneratedFileObject {
  lazy val dependencies: Seq[_root_.scalapb.GeneratedFileObject] = Seq(
    edu.uci.ics.amber.engine.architecture.sendsemantics.partitionings.PartitioningsProto,
    edu.uci.ics.amber.engine.common.virtualidentity.VirtualidentityProto,
    scalapb.options.ScalapbProto
  )
  lazy val messagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] =
    Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]](
      edu.uci.ics.amber.engine.architecture.worker.controlcommands.StartWorkerV2,
      edu.uci.ics.amber.engine.architecture.worker.controlcommands.PauseWorkerV2,
      edu.uci.ics.amber.engine.architecture.worker.controlcommands.ResumeWorkerV2,
      edu.uci.ics.amber.engine.architecture.worker.controlcommands.UpdateInputLinkingV2,
      edu.uci.ics.amber.engine.architecture.worker.controlcommands.AddPartitioningV2,
      edu.uci.ics.amber.engine.architecture.worker.controlcommands.WorkerExecutionCompletedV2,
      edu.uci.ics.amber.engine.architecture.worker.controlcommands.QueryStatisticsV2,
      edu.uci.ics.amber.engine.architecture.worker.controlcommands.QueryCurrentInputTupleV2,
      edu.uci.ics.amber.engine.architecture.worker.controlcommands.SendPythonUdfV2,
      edu.uci.ics.amber.engine.architecture.worker.controlcommands.ControlCommandV2Message
    )
  private lazy val ProtoBytes: _root_.scala.Array[Byte] =
      scalapb.Encoding.fromBase64(scala.collection.immutable.Seq(
  """CkJlZHUvdWNpL2ljcy9hbWJlci9lbmdpbmUvYXJjaGl0ZWN0dXJlL3dvcmtlci9jb250cm9sY29tbWFuZHMucHJvdG8SLGVkd
  S51Y2kuaWNzLmFtYmVyLmVuZ2luZS5hcmNoaXRlY3R1cmUud29ya2VyGkdlZHUvdWNpL2ljcy9hbWJlci9lbmdpbmUvYXJjaGl0Z
  WN0dXJlL3NlbmRzZW1hbnRpY3MvcGFydGl0aW9uaW5ncy5wcm90bxo1ZWR1L3VjaS9pY3MvYW1iZXIvZW5naW5lL2NvbW1vbi92a
  XJ0dWFsaWRlbnRpdHkucHJvdG8aFXNjYWxhcGIvc2NhbGFwYi5wcm90byIPCg1TdGFydFdvcmtlclYyIg8KDVBhdXNlV29ya2VyV
  jIiEAoOUmVzdW1lV29ya2VyVjIi4gEKFFVwZGF0ZUlucHV0TGlua2luZ1YyEmkKCmlkZW50aWZpZXIYASABKAsyNS5lZHUudWNpL
  mljcy5hbWJlci5lbmdpbmUuY29tbW9uLkFjdG9yVmlydHVhbElkZW50aXR5QhLiPw8SCmlkZW50aWZpZXLwAQFSCmlkZW50aWZpZ
  XISXwoKaW5wdXRfbGluaxgCIAEoCzItLmVkdS51Y2kuaWNzLmFtYmVyLmVuZ2luZS5jb21tb24uTGlua0lkZW50aXR5QhHiPw4SC
  WlucHV0TGlua/ABAVIJaW5wdXRMaW5rIt4BChFBZGRQYXJ0aXRpb25pbmdWMhJMCgN0YWcYASABKAsyLS5lZHUudWNpLmljcy5hb
  WJlci5lbmdpbmUuY29tbW9uLkxpbmtJZGVudGl0eUIL4j8IEgN0YWfwAQFSA3RhZxJ7CgxwYXJ0aXRpb25pbmcYAiABKAsyQS5lZ
  HUudWNpLmljcy5hbWJlci5lbmdpbmUuYXJjaGl0ZWN0dXJlLnNlbmRzZW1hbnRpY3MuUGFydGl0aW9uaW5nQhTiPxESDHBhcnRpd
  GlvbmluZ/ABAVIMcGFydGl0aW9uaW5nIhwKGldvcmtlckV4ZWN1dGlvbkNvbXBsZXRlZFYyIhMKEVF1ZXJ5U3RhdGlzdGljc1YyI
  hoKGFF1ZXJ5Q3VycmVudElucHV0VHVwbGVWMiJZCg9TZW5kUHl0aG9uVWRmVjISGgoDdWRmGAEgASgJQgjiPwUSA3VkZlIDdWRmE
  ioKCWlzX3NvdXJjZRgCIAEoCEIN4j8KEghpc1NvdXJjZVIIaXNTb3VyY2Ui6AkKEENvbnRyb2xDb21tYW5kVjIScgoMc3RhcnRfd
  29ya2VyGAEgASgLMjsuZWR1LnVjaS5pY3MuYW1iZXIuZW5naW5lLmFyY2hpdGVjdHVyZS53b3JrZXIuU3RhcnRXb3JrZXJWMkIQ4
  j8NEgtzdGFydFdvcmtlckgAUgtzdGFydFdvcmtlchJyCgxwYXVzZV93b3JrZXIYAiABKAsyOy5lZHUudWNpLmljcy5hbWJlci5lb
  mdpbmUuYXJjaGl0ZWN0dXJlLndvcmtlci5QYXVzZVdvcmtlclYyQhDiPw0SC3BhdXNlV29ya2VySABSC3BhdXNlV29ya2VyEnYKD
  XJlc3VtZV93b3JrZXIYAyABKAsyPC5lZHUudWNpLmljcy5hbWJlci5lbmdpbmUuYXJjaGl0ZWN0dXJlLndvcmtlci5SZXN1bWVXb
  3JrZXJWMkIR4j8OEgxyZXN1bWVXb3JrZXJIAFIMcmVzdW1lV29ya2VyEoIBChBhZGRfcGFydGl0aW9uaW5nGAQgASgLMj8uZWR1L
  nVjaS5pY3MuYW1iZXIuZW5naW5lLmFyY2hpdGVjdHVyZS53b3JrZXIuQWRkUGFydGl0aW9uaW5nVjJCFOI/ERIPYWRkUGFydGl0a
  W9uaW5nSABSD2FkZFBhcnRpdGlvbmluZxKPAQoUdXBkYXRlX2lucHV0X2xpbmtpbmcYBSABKAsyQi5lZHUudWNpLmljcy5hbWJlc
  i5lbmdpbmUuYXJjaGl0ZWN0dXJlLndvcmtlci5VcGRhdGVJbnB1dExpbmtpbmdWMkIX4j8UEhJ1cGRhdGVJbnB1dExpbmtpbmdIA
  FISdXBkYXRlSW5wdXRMaW5raW5nEoIBChBxdWVyeV9zdGF0aXN0aWNzGAYgASgLMj8uZWR1LnVjaS5pY3MuYW1iZXIuZW5naW5lL
  mFyY2hpdGVjdHVyZS53b3JrZXIuUXVlcnlTdGF0aXN0aWNzVjJCFOI/ERIPcXVlcnlTdGF0aXN0aWNzSABSD3F1ZXJ5U3RhdGlzd
  GljcxKgAQoZcXVlcnlfY3VycmVudF9pbnB1dF90dXBsZRgHIAEoCzJGLmVkdS51Y2kuaWNzLmFtYmVyLmVuZ2luZS5hcmNoaXRlY
  3R1cmUud29ya2VyLlF1ZXJ5Q3VycmVudElucHV0VHVwbGVWMkIb4j8YEhZxdWVyeUN1cnJlbnRJbnB1dFR1cGxlSABSFnF1ZXJ5Q
  3VycmVudElucHV0VHVwbGUSewoPc2VuZF9weXRob25fdWRmGBUgASgLMj0uZWR1LnVjaS5pY3MuYW1iZXIuZW5naW5lLmFyY2hpd
  GVjdHVyZS53b3JrZXIuU2VuZFB5dGhvblVkZlYyQhLiPw8SDXNlbmRQeXRob25VZGZIAFINc2VuZFB5dGhvblVkZhKnAQoad29ya
  2VyX2V4ZWN1dGlvbl9jb21wbGV0ZWQYZSABKAsySC5lZHUudWNpLmljcy5hbWJlci5lbmdpbmUuYXJjaGl0ZWN0dXJlLndvcmtlc
  i5Xb3JrZXJFeGVjdXRpb25Db21wbGV0ZWRWMkId4j8aEhh3b3JrZXJFeGVjdXRpb25Db21wbGV0ZWRIAFIYd29ya2VyRXhlY3V0a
  W9uQ29tcGxldGVkQg4KDHNlYWxlZF92YWx1ZUIJ4j8GSABYAHgBYgZwcm90bzM="""
      ).mkString)
  lazy val scalaDescriptor: _root_.scalapb.descriptors.FileDescriptor = {
    val scalaProto = com.google.protobuf.descriptor.FileDescriptorProto.parseFrom(ProtoBytes)
    _root_.scalapb.descriptors.FileDescriptor.buildFrom(scalaProto, dependencies.map(_.scalaDescriptor))
  }
  lazy val javaDescriptor: com.google.protobuf.Descriptors.FileDescriptor = {
    val javaProto = com.google.protobuf.DescriptorProtos.FileDescriptorProto.parseFrom(ProtoBytes)
    com.google.protobuf.Descriptors.FileDescriptor.buildFrom(javaProto, _root_.scala.Array(
      edu.uci.ics.amber.engine.architecture.sendsemantics.partitionings.PartitioningsProto.javaDescriptor,
      edu.uci.ics.amber.engine.common.virtualidentity.VirtualidentityProto.javaDescriptor,
      scalapb.options.ScalapbProto.javaDescriptor
    ))
  }
  @deprecated("Use javaDescriptor instead. In a future version this will refer to scalaDescriptor.", "ScalaPB 0.5.47")
  def descriptor: com.google.protobuf.Descriptors.FileDescriptor = javaDescriptor
}