// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package edu.uci.ics.amber.engine.common.workflowruntimestate

sealed abstract class FatalErrorType(val value: _root_.scala.Int) extends _root_.scalapb.GeneratedEnum {
  type EnumType = FatalErrorType
  def isCompilationError: _root_.scala.Boolean = false
  def isExecutionFailure: _root_.scala.Boolean = false
  def companion: _root_.scalapb.GeneratedEnumCompanion[FatalErrorType] = edu.uci.ics.amber.engine.common.workflowruntimestate.FatalErrorType
  final def asRecognized: _root_.scala.Option[edu.uci.ics.amber.engine.common.workflowruntimestate.FatalErrorType.Recognized] = if (isUnrecognized) _root_.scala.None else _root_.scala.Some(this.asInstanceOf[edu.uci.ics.amber.engine.common.workflowruntimestate.FatalErrorType.Recognized])
}

object FatalErrorType extends _root_.scalapb.GeneratedEnumCompanion[FatalErrorType] {
  sealed trait Recognized extends FatalErrorType
  implicit def enumCompanion: _root_.scalapb.GeneratedEnumCompanion[FatalErrorType] = this
  
  @SerialVersionUID(0L)
  case object COMPILATION_ERROR extends FatalErrorType(0) with FatalErrorType.Recognized {
    val index = 0
    val name = "COMPILATION_ERROR"
    override def isCompilationError: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object EXECUTION_FAILURE extends FatalErrorType(1) with FatalErrorType.Recognized {
    val index = 1
    val name = "EXECUTION_FAILURE"
    override def isExecutionFailure: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  final case class Unrecognized(unrecognizedValue: _root_.scala.Int) extends FatalErrorType(unrecognizedValue) with _root_.scalapb.UnrecognizedEnum
  lazy val values = scala.collection.immutable.Seq(COMPILATION_ERROR, EXECUTION_FAILURE)
  def fromValue(__value: _root_.scala.Int): FatalErrorType = __value match {
    case 0 => COMPILATION_ERROR
    case 1 => EXECUTION_FAILURE
    case __other => Unrecognized(__other)
  }
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.EnumDescriptor = WorkflowruntimestateProto.javaDescriptor.getEnumTypes().get(0)
  def scalaDescriptor: _root_.scalapb.descriptors.EnumDescriptor = WorkflowruntimestateProto.scalaDescriptor.enums(0)
}