# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: edu/uci/ics/amber/engine/common/ambermessage.proto, edu/uci/ics/amber/engine/common/virtualidentity.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto
from betterproto.grpc.grpclib_server import ServiceBase


@dataclass(eq=False, repr=False)
class ActorVirtualIdentity(betterproto.Message):
    """final case class ActorVirtualIdentity"""

    name: str = betterproto.string_field(1)


@dataclass(eq=False, repr=False)
class LayerIdentity(betterproto.Message):
    """
    final case class LayerIdentity (    workflow: String,    operator: String,
    layerID: String )
    """

    workflow: str = betterproto.string_field(1)
    operator: str = betterproto.string_field(2)
    layer_id: str = betterproto.string_field(3)


@dataclass(eq=False, repr=False)
class LinkIdentity(betterproto.Message):
    """
    final case class LinkIdentity (    from: LayerIdentity,    to:
    LayerIdentity )
    """

    from_: "LayerIdentity" = betterproto.message_field(1)
    from_port: int = betterproto.int32_field(2)
    to: "LayerIdentity" = betterproto.message_field(3)
    to_port: int = betterproto.int32_field(4)


@dataclass(eq=False, repr=False)
class OperatorIdentity(betterproto.Message):
    """
    final case class LinkIdentity (    workflow: String,    operator: String )
    """

    workflow: str = betterproto.string_field(1)
    operator: str = betterproto.string_field(2)


@dataclass(eq=False, repr=False)
class WorkflowIdentity(betterproto.Message):
    """final case class WorkflowIdentity (    id: String )"""

    id: str = betterproto.string_field(1)


@dataclass(eq=False, repr=False)
class ControlInvocationV2(betterproto.Message):
    command_id: int = betterproto.int64_field(1)
    command: "_architecture_worker__.ControlCommandV2" = betterproto.message_field(2)


@dataclass(eq=False, repr=False)
class ReturnInvocationV2(betterproto.Message):
    original_command_id: int = betterproto.int64_field(1)
    control_return: "_architecture_worker__.ControlReturnV2" = (
        betterproto.message_field(2)
    )


@dataclass(eq=False, repr=False)
class ControlPayloadV2(betterproto.Message):
    control_invocation: "ControlInvocationV2" = betterproto.message_field(
        1, group="sealed_value"
    )
    return_invocation: "ReturnInvocationV2" = betterproto.message_field(
        2, group="sealed_value"
    )


@dataclass(eq=False, repr=False)
class PythonDataHeader(betterproto.Message):
    tag: "ActorVirtualIdentity" = betterproto.message_field(1)
    is_end: bool = betterproto.bool_field(2)


@dataclass(eq=False, repr=False)
class PythonControlMessage(betterproto.Message):
    tag: "ActorVirtualIdentity" = betterproto.message_field(1)
    payload: "ControlPayloadV2" = betterproto.message_field(2)


from ..architecture import worker as _architecture_worker__
