// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package edu.uci.ics.amber.engine.common.virtualidentity

object VirtualidentityProto extends _root_.scalapb.GeneratedFileObject {
  lazy val dependencies: Seq[_root_.scalapb.GeneratedFileObject] = Seq(
    scalapb.options.ScalapbProto
  )
  lazy val messagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] =
    Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]](
      edu.uci.ics.amber.engine.common.virtualidentity.ActorVirtualIdentity,
      edu.uci.ics.amber.engine.common.virtualidentity.LayerIdentity,
      edu.uci.ics.amber.engine.common.virtualidentity.LinkIdentity,
      edu.uci.ics.amber.engine.common.virtualidentity.OperatorIdentity,
      edu.uci.ics.amber.engine.common.virtualidentity.WorkflowIdentity
    )
  private lazy val ProtoBytes: _root_.scala.Array[Byte] =
      scalapb.Encoding.fromBase64(scala.collection.immutable.Seq(
  """CjVlZHUvdWNpL2ljcy9hbWJlci9lbmdpbmUvY29tbW9uL3ZpcnR1YWxpZGVudGl0eS5wcm90bxIfZWR1LnVjaS5pY3MuYW1iZ
  XIuZW5naW5lLmNvbW1vbhoVc2NhbGFwYi9zY2FsYXBiLnByb3RvIjUKFEFjdG9yVmlydHVhbElkZW50aXR5Eh0KBG5hbWUYASABK
  AlCCeI/BhIEbmFtZVIEbmFtZSKNAQoNTGF5ZXJJZGVudGl0eRIpCgh3b3JrZmxvdxgBIAEoCUIN4j8KEgh3b3JrZmxvd1IId29ya
  2Zsb3cSKQoIb3BlcmF0b3IYAiABKAlCDeI/ChIIb3BlcmF0b3JSCG9wZXJhdG9yEiYKB2xheWVySUQYAyABKAlCDOI/CRIHbGF5Z
  XJJRFIHbGF5ZXJJRCKsAQoMTGlua0lkZW50aXR5ElAKBGZyb20YASABKAsyLi5lZHUudWNpLmljcy5hbWJlci5lbmdpbmUuY29tb
  W9uLkxheWVySWRlbnRpdHlCDOI/CRIEZnJvbfABAVIEZnJvbRJKCgJ0bxgCIAEoCzIuLmVkdS51Y2kuaWNzLmFtYmVyLmVuZ2luZ
  S5jb21tb24uTGF5ZXJJZGVudGl0eUIK4j8HEgJ0b/ABAVICdG8iaAoQT3BlcmF0b3JJZGVudGl0eRIpCgh3b3JrZmxvdxgBIAEoC
  UIN4j8KEgh3b3JrZmxvd1IId29ya2Zsb3cSKQoIb3BlcmF0b3IYAiABKAlCDeI/ChIIb3BlcmF0b3JSCG9wZXJhdG9yIisKEFdvc
  mtmbG93SWRlbnRpdHkSFwoCaWQYASABKAlCB+I/BBICaWRSAmlkQgniPwZIAFgAeAFiBnByb3RvMw=="""
      ).mkString)
  lazy val scalaDescriptor: _root_.scalapb.descriptors.FileDescriptor = {
    val scalaProto = com.google.protobuf.descriptor.FileDescriptorProto.parseFrom(ProtoBytes)
    _root_.scalapb.descriptors.FileDescriptor.buildFrom(scalaProto, dependencies.map(_.scalaDescriptor))
  }
  lazy val javaDescriptor: com.google.protobuf.Descriptors.FileDescriptor = {
    val javaProto = com.google.protobuf.DescriptorProtos.FileDescriptorProto.parseFrom(ProtoBytes)
    com.google.protobuf.Descriptors.FileDescriptor.buildFrom(javaProto, _root_.scala.Array(
      scalapb.options.ScalapbProto.javaDescriptor
    ))
  }
  @deprecated("Use javaDescriptor instead. In a future version this will refer to scalaDescriptor.", "ScalaPB 0.5.47")
  def descriptor: com.google.protobuf.Descriptors.FileDescriptor = javaDescriptor
}