package edu.uci.ics.texera.api.engine;

import edu.uci.ics.texera.api.dataflow.ISink;
import java.util.HashMap;

/**
 * Created by chenli on 5/11/16.
 * <p>
 * A query plan is a tree of operators except the root, which is an ISink object
 * that consumes all the tuples generated by its subtree.
 */
public class Plan {


    private final HashMap<String, ISink> sinkMap;

    public Plan(HashMap<String, ISink> sinkMap) {
        this.sinkMap = sinkMap;
    }

    public HashMap<String, ISink> getSinkMap() {
        return sinkMap;
    }


}
