/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

package org.apache.texera.amber.operator.machineLearning.Scorer

import com.fasterxml.jackson.annotation.{JsonProperty, JsonPropertyDescription}
import com.kjetland.jackson.jsonSchema.annotations.{
  JsonSchemaInject,
  JsonSchemaString,
  JsonSchemaTitle
}
import org.apache.texera.amber.core.tuple.{Attribute, AttributeType, Schema}
import org.apache.texera.amber.pybuilder.PythonTemplateBuilder.PythonTemplateBuilderStringContext
import org.apache.texera.amber.pybuilder.PyStringTypes.EncodableString
import org.apache.texera.amber.core.workflow.{InputPort, OutputPort, PortIdentity}
import org.apache.texera.amber.operator.{PythonOperatorDescriptor, StandaloneCodeGenerator}
import org.apache.texera.amber.operator.metadata.annotations.{
  AutofillAttributeName,
  HideAnnotation,
  SampleColumn
}
import org.apache.texera.amber.operator.metadata.{OperatorGroupConstants, OperatorInfo}
import org.apache.texera.amber.pybuilder.PythonTemplateBuilder.pyStringLiteral

// Whichever metric list the task shows must hold at least one metric: an empty
// one renders as `metric_list = ['']` and the metric lookup fails on the empty
// name. The rule is conditional because only one of the two lists is visible at
// a time, and a flat `required` on both can never be satisfied.
@JsonSchemaInject(json = """
{
  "allOf": [
    {
      "if": {
        "required": ["isRegression"],
        "properties": { "isRegression": { "const": false } }
      },
      "then": {
        "required": ["classificationFlag"],
        "properties": { "classificationFlag": { "minItems": 1 } }
      }
    },
    {
      "if": {
        "required": ["isRegression"],
        "properties": { "isRegression": { "const": true } }
      },
      "then": {
        "required": ["regressionFlag"],
        "properties": { "regressionFlag": { "minItems": 1 } }
      }
    }
  ]
}
""")
class MachineLearningScorerOpDesc extends PythonOperatorDescriptor with StandaloneCodeGenerator {
  @JsonProperty(required = true, defaultValue = "false")
  @JsonSchemaTitle("Regression")
  @JsonPropertyDescription(
    "Choose to solve a regression task"
  )
  var isRegression: Boolean = false

  @JsonProperty(required = true)
  @JsonSchemaTitle("Actual Value")
  @JsonPropertyDescription("Specify the label attribute")
  @AutofillAttributeName
  // Test-only steering: the pair has to be one label read twice, and the
  // first-unused pick names two unrelated columns.
  @SampleColumn("a\"b\\c_species")
  var actualValueColumn: EncodableString = ""

  @JsonProperty(required = true)
  @JsonSchemaTitle("Predicted Value")
  @JsonPropertyDescription("Specify the attribute generated by the model")
  @AutofillAttributeName
  @SampleColumn("a\"b\\c_species_pred")
  var predictValueColumn: EncodableString = ""

  @JsonProperty(required = false, value = "classificationFlag")
  @JsonSchemaTitle("Scorer Functions")
  @JsonPropertyDescription("Select classification tasks metrics")
  @JsonSchemaInject(
    strings = Array(
      new JsonSchemaString(path = HideAnnotation.hideTarget, value = "isRegression"),
      new JsonSchemaString(path = HideAnnotation.hideType, value = HideAnnotation.Type.equals),
      new JsonSchemaString(path = HideAnnotation.hideExpectedValue, value = "true")
    )
  )
  var classificationMetrics: List[classificationMetricsFnc] = List()

  @JsonProperty(required = false, value = "regressionFlag")
  @JsonSchemaTitle("Scorer Functions")
  @JsonPropertyDescription("Select regression tasks metrics")
  @JsonSchemaInject(
    strings = Array(
      new JsonSchemaString(path = HideAnnotation.hideTarget, value = "isRegression"),
      new JsonSchemaString(path = HideAnnotation.hideType, value = HideAnnotation.Type.equals),
      new JsonSchemaString(path = HideAnnotation.hideExpectedValue, value = "false")
    )
  )
  var regressionMetrics: List[regressionMetricsFnc] = List()

  override def operatorInfo: OperatorInfo =
    OperatorInfo(
      "Machine Learning Scorer",
      "Scorer for machine learning models",
      OperatorGroupConstants.MACHINE_LEARNING_GENERAL_GROUP,
      inputPorts = List(InputPort()),
      outputPorts = List(OutputPort())
    )

  /** The two scored columns hold one quantity measured twice, so they have to be
    * comparable. Left to sklearn, a mismatched pair either raises `Mix of label
    * input types` from deep inside a metric or, for Accuracy, quietly scores 0 —
    * neither of which points back at the two columns the user picked.
    *
    * Types only, not values: a DOUBLE label column of 0.0 / 1.0 is a legitimate
    * classification target even though a continuous one is not, and the schema
    * cannot tell the two apart.
    */
  private def validateScoredColumns(inputSchemas: Map[PortIdentity, Schema]): Unit = {
    val numeric = Set(AttributeType.INTEGER, AttributeType.LONG, AttributeType.DOUBLE)
    // Blank names are what the form reports before the user has picked; the
    // schema's own `required` already says so, and saying it twice would put a
    // second message on a half-filled operator.
    if (actualValueColumn.isEmpty || predictValueColumn.isEmpty) return
    inputSchemas.get(operatorInfo.inputPorts.head.id).foreach { schema =>
      Seq(("Actual Value", actualValueColumn), ("Predicted Value", predictValueColumn))
        .foreach {
          case (label, column) =>
            if (!schema.containsAttribute(column))
              throw new RuntimeException(s"$label column '$column' is not in the input table")
        }
      val actualType = schema.getAttribute(actualValueColumn).getType
      val predictType = schema.getAttribute(predictValueColumn).getType
      if (isRegression) {
        Seq(
          ("Actual Value", actualValueColumn, actualType),
          ("Predicted Value", predictValueColumn, predictType)
        )
          .foreach {
            case (label, column, attributeType) =>
              if (!numeric.contains(attributeType))
                throw new RuntimeException(
                  s"A regression metric needs a numeric $label column, but '$column' is " +
                    s"${attributeType.getName}"
                )
          }
      } else {
        val comparable = (numeric.contains(actualType) && numeric.contains(predictType)) ||
          actualType == predictType
        if (!comparable)
          throw new RuntimeException(
            s"Actual Value '$actualValueColumn' (${actualType.getName}) and Predicted Value " +
              s"'$predictValueColumn' (${predictType.getName}) hold different kinds of label, " +
              "so a classification metric cannot compare them"
          )
      }
    }
  }

  override def getOutputSchemas(
      inputSchemas: Map[PortIdentity, Schema]
  ): Map[PortIdentity, Schema] = {
    validateScoredColumns(inputSchemas)
    val metrics = if (isRegression) {
      regressionMetrics.map(_.getName())
    } else {
      classificationMetrics.map(_.getName())
    }
    val baseSchema = if (!isRegression) {
      Schema(List(new Attribute("Class", AttributeType.STRING)))
    } else {
      Schema(List())
    }

    val outputSchema = metrics.foldLeft(baseSchema) { (currentSchema, metricName) =>
      currentSchema.add(new Attribute(metricName, AttributeType.DOUBLE))
    }

    Map(operatorInfo.outputPorts.head.id -> outputSchema)
  }

//  private def getClassificationScorerName(scorer: classificationMetricsFnc): String = {
//    // Directly return the name of the scorer using the getName() method
//    scorer.getName()
//  }
//  private def getRegressionScorerName(scorer: regressionMetricsFnc): String = {
//    // Directly return the name of the scorer using the getName() method
//    scorer.getName()
//  }

  private def getMetricName(metric: Any): EncodableString =
    metric match {
      case m: regressionMetricsFnc     => m.getName()
      case m: classificationMetricsFnc => m.getName()
      case _                           => throw new IllegalArgumentException("Unknown metric type")
    }

  // Must be a plain String, not EncodableString: this is a raw Python fragment
  // spliced verbatim into `metric_list = [...]`. An EncodableString would be
  // re-encoded as one quoted value, collapsing the list into a single element.
  private def getSelectedMetrics(): String = {
    val metric = if (isRegression) regressionMetrics else classificationMetrics
    metric.map(metric => getMetricName(metric)).mkString("'", "','", "'")
  }

  override def generatePythonCode(): String = {
    val isRegressionStr = if (isRegression) "True" else "False"
    val finalcode =
      pyb"""
         |from pytexera import *
         |import pandas as pd
         |from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, mean_squared_error, root_mean_squared_error, mean_absolute_error, r2_score
         |
         |def classification_metrics(y_true, y_pred, metric_list, labels):
         |  if 'Accuracy' in metric_list:
         |    labels.insert(0, 'Overall')
         |  result = {metric: [None] * len(labels) for metric in metric_list}
         |  metrics_func = {'Precision Score': precision_score, 'Recall Score': recall_score, 'F1 Score': f1_score}
         |
         |  for metric in metric_list:
         |    prediction = None
         |    if metric == 'Accuracy':
         |      result['Accuracy'][0] = round(accuracy_score(y_true, y_pred), 4)
         |    else:
         |      for i, label in enumerate(labels):
         |        if label != 'Overall':
         |          prediction = metrics_func[metric](y_true, y_pred, average=None, labels=[label])
         |          result[metric][i] = round(prediction[0], 4)
         |
         |  # if the label is not a string, convert it to string
         |  labels = ['class_' + str(label) if type(label) != str else label for label in labels]
         |  result['Class'] = labels
         |  result_df = pd.DataFrame(result)
         |
         |  return result_df
         |
         |
         |def regression_metrics(y_true, y_pred, metric_list):
         |  result = dict()
         |  metrics_func = {'MSE': mean_squared_error, 'RMSE': root_mean_squared_error, 'MAE': mean_absolute_error, 'R2': r2_score}
         |  for metric in metric_list:
         |    result[metric] = metrics_func[metric](y_true, y_pred)
         |
         |  result_df = pd.DataFrame(result, index=[0])
         |
         |  return result_df
         |
         |class ProcessTableOperator(UDFTableOperator):
         |
         |    @overrides
         |    def process_table(self, table: Table, port: int) -> Iterator[Optional[TableLike]]:
         |      # A row missing either value has nothing to score, and the metrics
         |      # refuse the empty cell rather than passing over it.
         |      table = table.dropna(subset=[$actualValueColumn, $predictValueColumn])
         |      # Nothing survived the drop. The metrics answer that badly and each in
         |      # its own way: the regression ones raise from inside scikit-learn, and
         |      # the classification ones return a NaN score, which reads as a result.
         |      if table.empty:
         |        raise ValueError("No rows left to score: every row is missing the actual value, the predicted value, or both.")
         |      y_true = table[$actualValueColumn]
         |      y_pred = table[$predictValueColumn]
         |
         |      metric_list = [${getSelectedMetrics()}]
         |
         |      if $isRegressionStr:
         |        result = regression_metrics(y_true, y_pred, metric_list)
         |      else:
         |        # calculate the number of unique labels
         |        labels = list(set(y_true))
         |        result = classification_metrics(y_true, y_pred, metric_list, labels)
         |
         |      yield result
         |"""
    finalcode.encode
  }

  override def generateStandaloneCode(): String = {
    val isRegressionStr = if (isRegression) "True" else "False"
    s"""import pandas as pd
       |from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, mean_squared_error, root_mean_squared_error, mean_absolute_error, r2_score
       |
       |def classification_metrics(y_true, y_pred, metric_list, labels):
       |  if 'Accuracy' in metric_list:
       |    labels.insert(0, 'Overall')
       |  result = {metric: [None] * len(labels) for metric in metric_list}
       |  metrics_func = {'Precision Score': precision_score, 'Recall Score': recall_score, 'F1 Score': f1_score}
       |
       |  for metric in metric_list:
       |    if metric == 'Accuracy':
       |      result['Accuracy'][0] = round(accuracy_score(y_true, y_pred), 4)
       |    else:
       |      for i, label in enumerate(labels):
       |        if label != 'Overall':
       |          prediction = metrics_func[metric](y_true, y_pred, average=None, labels=[label])
       |          result[metric][i] = round(prediction[0], 4)
       |
       |  labels = ['class_' + str(label) if type(label) != str else label for label in labels]
       |  result['Class'] = labels
       |  # Class first and the metrics in the order they were picked, which is
       |  # the column order this operator declares and so the order of the rows
       |  # the workflow shows.
       |  return pd.DataFrame(result)[['Class'] + metric_list]
       |
       |def regression_metrics(y_true, y_pred, metric_list):
       |  result = dict()
       |  metrics_func = {'MSE': mean_squared_error, 'RMSE': root_mean_squared_error, 'MAE': mean_absolute_error, 'R2': r2_score}
       |  for metric in metric_list:
       |    result[metric] = metrics_func[metric](y_true, y_pred)
       |  return pd.DataFrame(result, index=[0])
       |
       |# Bound to a name of its own: the same frame can feed another branch of the
       |# plan, which must still see every row.
       |scored_df = in1df.dropna(subset=[${pyStringLiteral(actualValueColumn)}, ${pyStringLiteral(
      predictValueColumn
    )}])
       |# Nothing survived the drop. The metrics answer that badly and each in its own
       |# way: the regression ones raise from inside scikit-learn, and the
       |# classification ones return a NaN score, which reads as a result.
       |if scored_df.empty:
       |    raise ValueError("No rows left to score: every row is missing the actual value, the predicted value, or both.")
       |y_true = scored_df[${pyStringLiteral(actualValueColumn)}]
       |y_pred = scored_df[${pyStringLiteral(predictValueColumn)}]
       |metric_list = [${getSelectedMetrics()}]
       |if $isRegressionStr:
       |    out1df = regression_metrics(y_true, y_pred, metric_list)
       |else:
       |    labels = list(set(y_true))
       |    out1df = classification_metrics(y_true, y_pred, metric_list, labels)""".stripMargin
  }

}
