// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package edu.uci.ics.texera.web.workflowruntimestate

object WorkflowruntimestateProto extends _root_.scalapb.GeneratedFileObject {
  lazy val dependencies: Seq[_root_.scalapb.GeneratedFileObject] = Seq(
    edu.uci.ics.amber.engine.architecture.worker.controlreturns.ControlreturnsProto,
    scalapb.options.ScalapbProto
  )
  lazy val messagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] =
    Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]](
      edu.uci.ics.texera.web.workflowruntimestate.BreakpointFault,
      edu.uci.ics.texera.web.workflowruntimestate.OperatorBreakpoints,
      edu.uci.ics.texera.web.workflowruntimestate.JobBreakpointStore,
      edu.uci.ics.texera.web.workflowruntimestate.EvaluatedValueList,
      edu.uci.ics.texera.web.workflowruntimestate.PythonOperatorInfo,
      edu.uci.ics.texera.web.workflowruntimestate.JobPythonStore,
      edu.uci.ics.texera.web.workflowruntimestate.OperatorRuntimeStats,
      edu.uci.ics.texera.web.workflowruntimestate.JobStatsStore,
      edu.uci.ics.texera.web.workflowruntimestate.JobMetadataStore
    )
  private lazy val ProtoBytes: _root_.scala.Array[Byte] =
      scalapb.Encoding.fromBase64(scala.collection.immutable.Seq(
  """Ci1lZHUvdWNpL2ljcy90ZXhlcmEvd29ya2Zsb3dydW50aW1lc3RhdGUucHJvdG8SFmVkdS51Y2kuaWNzLnRleGVyYS53ZWIaQ
  WVkdS91Y2kvaWNzL2FtYmVyL2VuZ2luZS9hcmNoaXRlY3R1cmUvd29ya2VyL2NvbnRyb2xyZXR1cm5zLnByb3RvGhVzY2FsYXBiL
  3NjYWxhcGIucHJvdG8i0wIKD0JyZWFrcG9pbnRGYXVsdBItCgphY3Rvcl9wYXRoGAEgASgJQg7iPwsSCWFjdG9yUGF0aFIJYWN0b
  3JQYXRoEm8KDWZhdWx0ZWRfdHVwbGUYAiABKAsyNy5lZHUudWNpLmljcy50ZXhlcmEud2ViLkJyZWFrcG9pbnRGYXVsdC5CcmVha
  3BvaW50VHVwbGVCEeI/DhIMZmF1bHRlZFR1cGxlUgxmYXVsdGVkVHVwbGUSKQoIbWVzc2FnZXMYAyADKAlCDeI/ChIIbWVzc2FnZ
  XNSCG1lc3NhZ2VzGnUKD0JyZWFrcG9pbnRUdXBsZRIXCgJpZBgBIAEoA0IH4j8EEgJpZFICaWQSJwoIaXNfaW5wdXQYAiABKAhCD
  OI/CRIHaXNJbnB1dFIHaXNJbnB1dBIgCgV0dXBsZRgDIAMoCUIK4j8HEgV0dXBsZVIFdHVwbGUikQEKE09wZXJhdG9yQnJlYWtwb
  2ludHMSegoWdW5yZXNvbHZlZF9icmVha3BvaW50cxgBIAMoCzInLmVkdS51Y2kuaWNzLnRleGVyYS53ZWIuQnJlYWtwb2ludEZhd
  Wx0QhriPxcSFXVucmVzb2x2ZWRCcmVha3BvaW50c1IVdW5yZXNvbHZlZEJyZWFrcG9pbnRzIo8CChJKb2JCcmVha3BvaW50U3Rvc
  mUSdAoNb3BlcmF0b3JfaW5mbxgBIAMoCzI8LmVkdS51Y2kuaWNzLnRleGVyYS53ZWIuSm9iQnJlYWtwb2ludFN0b3JlLk9wZXJhd
  G9ySW5mb0VudHJ5QhHiPw4SDG9wZXJhdG9ySW5mb1IMb3BlcmF0b3JJbmZvGoIBChFPcGVyYXRvckluZm9FbnRyeRIaCgNrZXkYA
  SABKAlCCOI/BRIDa2V5UgNrZXkSTQoFdmFsdWUYAiABKAsyKy5lZHUudWNpLmljcy50ZXhlcmEud2ViLk9wZXJhdG9yQnJlYWtwb
  2ludHNCCuI/BxIFdmFsdWVSBXZhbHVlOgI4ASJ3ChJFdmFsdWF0ZWRWYWx1ZUxpc3QSYQoGdmFsdWVzGAEgAygLMjwuZWR1LnVja
  S5pY3MuYW1iZXIuZW5naW5lLmFyY2hpdGVjdHVyZS53b3JrZXIuRXZhbHVhdGVkVmFsdWVCC+I/CBIGdmFsdWVzUgZ2YWx1ZXMi9
  AIKElB5dGhvbk9wZXJhdG9ySW5mbxI/ChBjb25zb2xlX21lc3NhZ2VzGAEgAygJQhTiPxESD2NvbnNvbGVNZXNzYWdlc1IPY29uc
  29sZU1lc3NhZ2VzEpEBChVldmFsdWF0ZV9leHByX3Jlc3VsdHMYAiADKAsyQy5lZHUudWNpLmljcy50ZXhlcmEud2ViLlB5dGhvb
  k9wZXJhdG9ySW5mby5FdmFsdWF0ZUV4cHJSZXN1bHRzRW50cnlCGOI/FRITZXZhbHVhdGVFeHByUmVzdWx0c1ITZXZhbHVhdGVFe
  HByUmVzdWx0cxqIAQoYRXZhbHVhdGVFeHByUmVzdWx0c0VudHJ5EhoKA2tleRgBIAEoCUII4j8FEgNrZXlSA2tleRJMCgV2YWx1Z
  RgCIAEoCzIqLmVkdS51Y2kuaWNzLnRleGVyYS53ZWIuRXZhbHVhdGVkVmFsdWVMaXN0QgriPwcSBXZhbHVlUgV2YWx1ZToCOAEih
  gIKDkpvYlB5dGhvblN0b3JlEnAKDW9wZXJhdG9yX2luZm8YASADKAsyOC5lZHUudWNpLmljcy50ZXhlcmEud2ViLkpvYlB5dGhvb
  lN0b3JlLk9wZXJhdG9ySW5mb0VudHJ5QhHiPw4SDG9wZXJhdG9ySW5mb1IMb3BlcmF0b3JJbmZvGoEBChFPcGVyYXRvckluZm9Fb
  nRyeRIaCgNrZXkYASABKAlCCOI/BRIDa2V5UgNrZXkSTAoFdmFsdWUYAiABKAsyKi5lZHUudWNpLmljcy50ZXhlcmEud2ViLlB5d
  Ghvbk9wZXJhdG9ySW5mb0IK4j8HEgV2YWx1ZVIFdmFsdWU6AjgBItABChRPcGVyYXRvclJ1bnRpbWVTdGF0cxJRCgVzdGF0ZRgBI
  AEoDjIvLmVkdS51Y2kuaWNzLnRleGVyYS53ZWIuV29ya2Zsb3dBZ2dyZWdhdGVkU3RhdGVCCuI/BxIFc3RhdGVSBXN0YXRlEjAKC
  2lucHV0X2NvdW50GAIgASgDQg/iPwwSCmlucHV0Q291bnRSCmlucHV0Q291bnQSMwoMb3V0cHV0X2NvdW50GAMgASgDQhDiPw0SC
  291dHB1dENvdW50UgtvdXRwdXRDb3VudCKGAgoNSm9iU3RhdHNTdG9yZRJvCg1vcGVyYXRvcl9pbmZvGAMgAygLMjcuZWR1LnVja
  S5pY3MudGV4ZXJhLndlYi5Kb2JTdGF0c1N0b3JlLk9wZXJhdG9ySW5mb0VudHJ5QhHiPw4SDG9wZXJhdG9ySW5mb1IMb3BlcmF0b
  3JJbmZvGoMBChFPcGVyYXRvckluZm9FbnRyeRIaCgNrZXkYASABKAlCCOI/BRIDa2V5UgNrZXkSTgoFdmFsdWUYAiABKAsyLC5lZ
  HUudWNpLmljcy50ZXhlcmEud2ViLk9wZXJhdG9yUnVudGltZVN0YXRzQgriPwcSBXZhbHVlUgV2YWx1ZToCOAEiowEKEEpvYk1ld
  GFkYXRhU3RvcmUSUQoFc3RhdGUYASABKA4yLy5lZHUudWNpLmljcy50ZXhlcmEud2ViLldvcmtmbG93QWdncmVnYXRlZFN0YXRlQ
  griPwcSBXN0YXRlUgVzdGF0ZRIgCgVlcnJvchgCIAEoCUIK4j8HEgVlcnJvclIFZXJyb3ISGgoDZWlkGAMgASgDQgjiPwUSA2VpZ
  FIDZWlkKqQBChdXb3JrZmxvd0FnZ3JlZ2F0ZWRTdGF0ZRIRCg1VTklOSVRJQUxJWkVEEAASCQoFUkVBRFkQARILCgdSVU5OSU5HE
  AISCwoHUEFVU0lORxADEgoKBlBBVVNFRBAEEgwKCFJFU1VNSU5HEAUSDgoKUkVDT1ZFUklORxAGEg0KCUNPTVBMRVRFRBAHEgsKB
  0FCT1JURUQQCBILCgdVTktOT1dOEAlCCeI/BkgAWAB4AGIGcHJvdG8z"""
      ).mkString)
  lazy val scalaDescriptor: _root_.scalapb.descriptors.FileDescriptor = {
    val scalaProto = com.google.protobuf.descriptor.FileDescriptorProto.parseFrom(ProtoBytes)
    _root_.scalapb.descriptors.FileDescriptor.buildFrom(scalaProto, dependencies.map(_.scalaDescriptor))
  }
  lazy val javaDescriptor: com.google.protobuf.Descriptors.FileDescriptor = {
    val javaProto = com.google.protobuf.DescriptorProtos.FileDescriptorProto.parseFrom(ProtoBytes)
    com.google.protobuf.Descriptors.FileDescriptor.buildFrom(javaProto, _root_.scala.Array(
      edu.uci.ics.amber.engine.architecture.worker.controlreturns.ControlreturnsProto.javaDescriptor,
      scalapb.options.ScalapbProto.javaDescriptor
    ))
  }
  @deprecated("Use javaDescriptor instead. In a future version this will refer to scalaDescriptor.", "ScalaPB 0.5.47")
  def descriptor: com.google.protobuf.Descriptors.FileDescriptor = javaDescriptor
}