package edu.uci.ics.textdb.api.dataflow;

/**
 * Created by chenli on 5/11/16.
 *
 * An ISink object is used as the root of a query plan tree to consume all the
 * tuples generated by its subtree.
 *
 */
public interface ISink {
    void open() throws Exception;


    void processTuples() throws Exception;


    void close() throws Exception;
}
